// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd8_juAGnl2vbuEMn-BHXWEpXdMN2GDxc',
    appId: '1:436717388929:web:b2cc3acf8b5f0288d37980',
    messagingSenderId: '436717388929',
    projectId: 'lusid-55',
    authDomain: 'lusid-55.firebaseapp.com',
    storageBucket: 'lusid-55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAezNdExsMf8OYWL108FjgJ2lC2vglWrRU',
    appId: '1:436717388929:android:2ff003f19c2eeb20d37980',
    messagingSenderId: '436717388929',
    projectId: 'lusid-55',
    storageBucket: 'lusid-55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtQfPvLI-kL2Pnyy2ck0_nVJWeNICr12k',
    appId: '1:436717388929:ios:199be87426e472d6d37980',
    messagingSenderId: '436717388929',
    projectId: 'lusid-55',
    storageBucket: 'lusid-55.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtQfPvLI-kL2Pnyy2ck0_nVJWeNICr12k',
    appId: '1:436717388929:ios:199be87426e472d6d37980',
    messagingSenderId: '436717388929',
    projectId: 'lusid-55',
    storageBucket: 'lusid-55.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd8_juAGnl2vbuEMn-BHXWEpXdMN2GDxc',
    appId: '1:436717388929:web:f9d4af72752f0f5ad37980',
    messagingSenderId: '436717388929',
    projectId: 'lusid-55',
    authDomain: 'lusid-55.firebaseapp.com',
    storageBucket: 'lusid-55.firebasestorage.app',
  );

}